## ===============================
## = DATA SOURCE
## ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gogobled
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 482B4B6250655368566D597133743677397A24432646294A404E635166546A57
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days